/** POSTS TYPES CONST*/
export const REQUEST_POSTS = "POST/REQUEST_POSTS";
export const SHOW_LOADER = "POST/SHOW_LOADER";
export const HIDE_LOADER = "POST/HIDE_LOADER";
export const FETCH_POSTS = "POST/FETCH_POSTS";
export const SAVE_ERROR_POSTS = "POST/SAVE_ERROR_POSTS";
/** _COMMENT TYPES CONST*/
export const SHOW_LOADER_COMMENT = "SHOW_LOADER_COMMENT";
export const HIDE_LOADER_COMMENT = "HIDE_LOADER_COMMENT";
export const REQUEST_COMMENTS = "COMMENTS/REQUEST_COMMENTS";
export const FETCH_COMMENTS = "COMMENTS/FETCH_COMMENTS";
export const SAVE_ERROR_COMMENT = "COMMENTS/SAVE_ERROR_COMMENT";
/** USER TYPES CONST*/
export const SHOW_LOADER_USER = "SHOW_LOADER_USER";
export const HIDE_LOADER_USER = "HIDE_LOADER_USER";
export const REQUEST_USER = "USER/REQUEST_USER";
export const FETCH_USER = "USER/FETCH_USER";
export const USER_ERROR_COMMENT = "USER/USER_ERROR_COMMENT";